version: "2"

services:
  network-optimizer:
    image: ghcr.io/ozark-connect/network-optimizer:1.17.2@sha256:3cfb5d0c44b8edcb7a3bb00b16b5658e3b63d740ce9a2395e88fb13aa6d9a520
    network_mode: host
    volumes:
      - data:/app/data
      - ssh-keys:/app/ssh-keys:ro
      - logs:/app/logs
    environment:
      BIND_LOCALHOST_ONLY: "false"
      OPENSPEEDTEST_HTTPS: "false"
      OPENSPEEDTEST_PORT: "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8042/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  speedtest:
    image: ghcr.io/ozark-connect/speedtest:1.17.2@sha256:b2c5de654b9abaade00f55ac894a7fc525f2fdcf61fa97c1378f4574a3f32256
    ports:
      - "3000:3000"

volumes:
  data: {}
  ssh-keys: {}
  logs: {}
