version: "2"

services:
  network-optimizer:
    image: ghcr.io/ozark-connect/network-optimizer:1.16.9@sha256:3880b045c5cd1a43b10722f5660f7cc5ef7419a45f9a4cc7b6ac59c257a1cbf2
    network_mode: host
    volumes:
      - data:/app/data
      - ssh-keys:/app/ssh-keys:ro
      - logs:/app/logs
    environment:
      BIND_LOCALHOST_ONLY: "false"
      OPENSPEEDTEST_HTTPS: "false"
      OPENSPEEDTEST_PORT: "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8042/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  speedtest:
    image: ghcr.io/ozark-connect/speedtest:1.16.9@sha256:3e7a166d0657aca4d2e41e59873786e6921c2b3a1fa54b3a3ea0da916bb9fe75
    ports:
      - "3000:3000"

volumes:
  data: {}
  ssh-keys: {}
  logs: {}
