version: "2"

services:
  network-optimizer:
    image: ghcr.io/ozark-connect/network-optimizer:1.20.1@sha256:27c1eb657c9348cf3a09085ceb723d373ab912fcc65df6e0849ac2beb0f2ec2e
    network_mode: host
    volumes:
      - data:/app/data
      - ssh-keys:/app/ssh-keys:ro
      - logs:/app/logs
    environment:
      BIND_LOCALHOST_ONLY: "false"
      OPENSPEEDTEST_HTTPS: "false"
      OPENSPEEDTEST_PORT: "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8042/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  speedtest:
    image: ghcr.io/ozark-connect/speedtest:1.20.1@sha256:f41d33532cdfc231a1e6af36cbeb49390107561fa8dab3cdd24d9f8187914bd2
    ports:
      - "3000:3000"

volumes:
  data: {}
  ssh-keys: {}
  logs: {}
